src/app/components/Header.tsx
src/app/components/LogoutBtn.tsx
src/app/components/Navbar.tsx
src/app/layout.tsx
src/app/page.tsx

Created Navbar and LogoutBtn as well.

AP-142 Implement header component

---

README.md
src/app/components/LogoutBtn.tsx
src/app/globals.css

https://dortchlindsey.atlassian.net/browse/AP-174?atlOrigin=eyJpIjoiYzAyZjM3ZjAxNmQ2NDk1MWJhYmQ2MTRhZWU5Y2NmM2IiLCJwIjoiaiJ9
primary-green
secondary-blue
alternate-green
primary-black
secondary-dark-gray
alternate-gray
alternate-light-gray

Ap 174 tailwind config

---

README.md

Added a Jira/GitHub workflow for team contributions.

chore: Add Jira/GitHub workflow to README (AP-176)

---

src/app/components/Navbar.tsx
src/app/components/NotificationBadge.tsx

Include a smaller font size for large number values.

Create NotificationBadge and add it to Navbar

---

src/app/components/MobileNav.tsx

Add the notification badge to the mobile nav.  Use conditional logic so it is rendered for the messages link.

Ap 193 mobile nav notification badge

---

src/app/page.tsx

basically just adding in Damien's latest PR and Andrew's latest PR into the landing page located at` /page.tsx`

Moved <ContactUs> and <Header> Component into landing page (AP-183)

---

src/app/components/FeatureCard.tsx
src/app/components/FeatureHighlight.tsx
src/app/constants/labels.ts
src/app/page.tsx

In this PR I created `Feature Highlight` section for the `landing page`.
To do this I:
- Created `Feature Card`.
- Created `Feature Highlight` section.
- Added Label map for `Feature Highlight`. 
- added the `Feature Highlight` section to `page.tsx` for the `landing page`.
- Used tailwind so that each `Feature Card` is responsive.

feat: created feature highlight section and cards. (AP-177)

---

jest.config.js
jest.setup.js
package-lock.json
package.json
src/app/components/GuestParkingPassForm.tsx
src/app/components/__tests__/GuestParkingPassForm.test.tsx
src/app/constants/labels.ts
src/app/hooks/useTanstackForm.ts
src/app/parking/page.tsx

It is mobile responsive and has the logic for entry but does require the API to be attached.

feat: parking pass feature with functionality. (AP-199)

---

src/app/Messaging/page.tsx
src/app/api/messages/route.ts
src/app/components/GuestParkingPassForm.tsx
src/app/components/__tests__/ComposeMessage.test.tsx
src/app/components/__tests__/MessageList.test.tsx
src/app/components/messaging/ComposeMessage.tsx
src/app/components/messaging/MessageList.tsx
src/app/constants/icons.ts
src/app/constants/labels.ts
src/app/parking/page.tsx
src/app/tenant/page.tsx

Mobile responsive in both states and using local storage and mocking the messages in routes.ts

feat: messaging and contact flow for tenants (AP-202)

---

src/app/components/Navbar.tsx

Used the same code from the LogoutBtn component.

feat: add logout functionality to mobile nav (AP-163)

---

src/app/components/ContactUs.tsx
src/app/components/Lock.tsx
src/app/constants/labels.ts
src/app/passkey/[id]/page.tsx
src/app/passkey/page.tsx

mentioned in meeting, styling of form input border
Feat: Created passkey directory and functioning lock and guest keys

feat: add lock UI, generate code, view code and send code (AP-201)

---

src/app/components/CompanyLogo.tsx
src/app/components/Header.tsx

The Header should be consistently styled for all pages.

fix: remove responsive colors in Header (TP-36)

---

pages/api/contact/[id].ts
pages/api/contact/index.ts
src/app/components/ContactUs.tsx

Added option to create, view, view by id and delete for contact us form
Added functionality in the front end to post the contact us form

TP-27 contact us form

---

src/app/components/Header.tsx

For mobile screens, the Guest Parking button just says 'Parking' for spacing.

feat: implement dynamic content for header based on auth status (TP-22)

---

src/app/components/CreateTenantForm.tsx
src/app/constants/labels.ts
src/app/createTenant/page.tsx

This PR adds the `Create Tenant Form` using TanStack form.
The form includes: 
- Fields for tenant details: First Name, Last Name, Email, and Apartment Number.
- Validation rules: required fields, min length.
- Error messages.
- Styling to march the figma design.

FEAT: Implemented Create Tenant Form (TP-43)

---

src/app/components/ContactUs.tsx

Added more validation to phone number input and the type attribute to the input.  Form submission should be disabled if any input is invalid:

fix: add type tel to input for phone number (TP-46)

---

src/app/components/EditProfileForm.tsx

Mock user data is pulled from useForm hook.  State is used to determine if the value of the email field is different from the user's email.  Check password field is conditionally rendered based on the boolean in isEmailChanged state.

feat: conditionally render the check password field based on the email field value (TP-76)

---

src/app/components/EditProfileForm.tsx
src/app/constants/labels.ts

This button does not function yet.  That will be a different PR.

feat: add change password btn to EditProfileForm (TP-65)

---

src/app/dashboard/page.tsx

In this PR the `report a noise complaint` link in the dashboard was changed to a button.  A POST request to make a complaint is now sent to the database when the user clicks on it.
Note: my prettier made some changes with quote marks. I just noticed it

CHORE: Change noise complaint to button and make POST request (TP-83)

---

src/app/dashboard/page.tsx

replaced animal user image with responsive user icons

feat: implement user profile icon tenant/admin dashboard (TP-91)

---

src/app/components/ErrorPage.tsx
src/app/components/LoadingPage.tsx
src/app/hooks/useAuth.ts

This useAuth hook can be imported into any client page/component to check if the user is authenticated in appwrite.  It returns user, loading, and error states:
There are also LoadingPage and ErrorPage components which accept optional messages:
LoadingPage:
ErrorPage:

feat: create useAuth hook (TP-89)

---

pages/api/users/[id].ts
src/app/components/CreateTenantForm.tsx
src/app/components/EditProfileForm.tsx
src/app/constants/labels.ts
src/app/success/page.tsx

- added update user profile function in the front end
- modified backend endpoint to split name into name and last name
- added password  and .com validation on create tenant form

TP-80 Update user profile on DB

---

pages/api/admin/lease/index.ts
src/app/components/CreateTenantForm.tsx
src/app/components/lease/GenerateLeaseForm.tsx
src/app/constants/labels.ts

Fixed validation for lease POST 
Fixed create Tenant password validation for 8 characters minimum

TP-100 Fixe endpoint validation for lease

---

src/app/components/Navbar.tsx
src/app/constants/labels.ts

Admin links in navbar should be same as dashboard buttons

TP-87 Add conditional rendering on nav links according to user role 

---

src/app/components/Header.tsx

Made button a Link so it can redirect to Generate Guest Parking

fix: guest parking navigation (TP-110)

---

src/app/constants/labels.ts

chore: remove admin dashboard button for guest parking (TP-111)

---

src/app/components/GuestParkingPassForm.tsx

chore: remove QR code place holder in generated parking pass (TP-82)

---

src/app/components/ChangePasswordForm.tsx
src/lib/appwrite.ts

On successful password change, the user is routed to the dashboard.

feat: implement onSubmit logic for ChangePasswordForm (TP-69)

---

src/app/components/ParkingLimitContainer.tsx
src/app/components/ParkingPassCard.tsx
src/app/constants/labels.ts
src/app/dashboard/page.tsx

This PR Introduces a `ParkingPassCard` on the inside of a `ParkingLimitContainer` 
The `ParkingLimitContainer` fetches the latest 2 parking passes created in the database for the user. 
`ParkingPassCard` pulls important data from the database and contains a countdown to show if the pass has expired. If the countdown hits `0`, Then the `expirationStatus` is changed to `Expired` and the pass changes to gray.
I've added a button to expire a pass manually so that we can demo the change.
Note: The Ability to delete a pass is not working on this PR

FEAT: Added Parking Pass Component to Dashboard (TP-104)

---

src/app/login/page.tsx

Redirected contact us link on login page to contact us form on landing page

Bug:fix contact us link in login page TP-85

---

src/app/components/GuestParkingPassForm.tsx

Added user validation for `GuestParkingPassForm`  If we get a 404 status back from our endpoint, then we'll display `User not found. Please check Tenant Last Name and Resident Apartment Number.` 
otherwise, if the tenant last name and apartment number are correct, then we will successfully create a parking pass.

chore: added user validation to parking pass form (TP-107)

---

src/app/components/Toast.tsx
src/app/dashboard/page.tsx
src/lib/appwrite.ts

This PR introduces Toast Component for the Noise Complaint Button. Toast appears after successful POST request and has a fade out effect to disappear after 4 seconds.
Toast Message was tested for Desktop and Mobile edge cases

Feat: Complaint Toast Message TP 96

---

src/app/dashboard/page.tsx

Updated property into font to semibold. The property info is easier to read now:

chore: update property info font to semibold (TP-119)

---

src/app/components/voicechat/Message.tsx
src/app/components/voicechat/voiceChatButton.tsx
src/app/components/voicechat/voiceChatModal.tsx
src/app/dashboard/page.tsx

Styled dashboard buttons, edit profile button, AI chat button, AI chat messages (TP-117)

Chore: Dashboard UI stying/branding (TP-117)

---

pages/api/admin/notifications/index.ts
pages/api/notifications/index.ts

Created a patch method to update message status from unread to read for toggle button

TP-126 patch endpoints for notification message when using the accordion 

---

src/app/locker/page.tsx

chore:add redirect to messaging from Contact Leasing button in packag…TP-102

---

pages/api/admin/notifications/index.ts
pages/api/notifications/index.ts
pages/api/users/index.ts
src/app/components/messaging/ComposeMessage.tsx
src/app/components/messaging/MessageList.tsx
src/app/login/page.tsx

Me and Cass were working on create a list of tenants so that admin can send message to different tenants>
Added dropdown list to show list of tenants
Updated backed  POST Method with find receiver function
Updated UI to show from Admin or From apt

TP-109 Added dropdown list on admin page for notification to show a list of tenants

---

src/app/components/PackageCard.tsx
src/app/constants/labels.ts
src/app/locker/page.tsx
src/types/package.ts
utils/formatDate.ts

- Packages are now grabbing data from the database.
- Color is rendering based on status
- Icons updated to reflect info from the database.
- Added format date util for an easier way to format ISO date that we get from the database.

fix: packages are rendering based on status. (TP-127)

---

src/app/components/Lock.tsx
src/app/constants/labels.ts
src/app/passkey/[id]/page.tsx
src/app/passkey/page.tsx

FE styling of door lock feature

chore: updated styling on door lock feature and guest passkey (TP-133)

---

pages/api/package/[id].ts
src/app/components/LockerDetails.tsx
src/app/locker/[id]/page.tsx
src/types/package.ts

- Added dynamic API route `[id]` to fetch individual package data based on its ID
- Styled Package Details Page

fix: get package details page (TP-130)

---

src/app/components/CompanyLogo.tsx
src/app/components/Footer.tsx

chore: add color prop to logo in footer
